Initial commit for CI/CD pipeline with Docker

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -59,40 +59,40 @@ jobs:
           username: ${{ secrets.DROPLET_USER }}
           key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
           script: |
-            # Update and install Docker if it's not installed
-            sudo apt update
-            sudo apt install -y docker.io
-            sudo systemctl start docker
-            sudo systemctl enable docker
+            # # Update and install Docker if it's not installed
+            # sudo apt update
+            # sudo apt install -y docker.io
+            # sudo systemctl start docker
+            # sudo systemctl enable docker
 
-            # Docker login to pull the image from DockerHub
-            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
+            # # Docker login to pull the image from DockerHub
+            # echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
 
-            # Pull the latest Docker image
-            docker pull frengkysorituamanurung/sample-app:latest
+            # # Pull the latest Docker image
+            # docker pull frengkysorituamanurung/sample-app:latest
 
-            # Stop and remove the existing container if it's running
-            docker stop myapp || true
-            docker rm myapp || true
+            # # Stop and remove the existing container if it's running
+            # docker stop myapp || true
+            # docker rm myapp || true
 
-            # Run the new container
-            docker run -d -p 80:80 --name myapp frengkysorituamanurung/sample-app:latest
-s           sh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} '
-            # Update the system and install Docker if not installed
-            if ! [ -x "$(command -v docker)" ]; then
-              echo "Docker not found, installing..."
-              sudo apt-get update &&
-              sudo apt-get install -y docker.io &&
-              sudo systemctl start docker &&
-              sudo systemctl enable docker
-            else
-              echo "Docker already installed."
-            fi
+            # # Run the new container
+            # #docker run -d -p 80:80 --name myapp frengkysorituamanurung/sample-app:latest
+s             sh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} '
+              # Update the system and install Docker if not installed
+              if ! [ -x "$(command -v docker)" ]; then
+                echo "Docker not found, installing..."
+                sudo apt-get update &&
+                sudo apt-get install -y docker.io &&
+                sudo systemctl start docker &&
+                sudo systemctl enable docker
+              else
+                echo "Docker already installed."
+              fi
 
-            # Pull the latest Docker image from registry
-            docker pull frengkysorituamanurung/sample-app:latest
+              # Pull the latest Docker image from registry
+              docker pull frengkysorituamanurung/sample-app:latest
 
 
-            # Run the new Docker container
-            docker run -d --name sample-app -p 80:80 frengkysorituamanurung/sample-app:latest
-          '
+              # Run the new Docker container
+              docker run -d --name sample-app -p 80:80 frengkysorituamanurung/sample-app:latest
+            '
