Initial commit for CI/CD pipeline with Docker

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -42,6 +42,11 @@ jobs:
       with:
         push: true
         tags: frengkysorituamanurung/sample-app:latest
+    
+    - name: Set up SSH agent
+      uses: webfactory/ssh-agent@v0.5.3
+      with:
+          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
 
   deploy:
     needs: build
@@ -72,3 +77,22 @@ jobs:
 
             # Run the new container
             docker run -d -p 80:80 --name myapp frengkysorituamanurung/sample-app:latest
+s           sh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} '
+            # Update the system and install Docker if not installed
+            if ! [ -x "$(command -v docker)" ]; then
+              echo "Docker not found, installing..."
+              sudo apt-get update &&
+              sudo apt-get install -y docker.io &&
+              sudo systemctl start docker &&
+              sudo systemctl enable docker
+            else
+              echo "Docker already installed."
+            fi
+
+            # Pull the latest Docker image from registry
+            docker pull frengkysorituamanurung/sample-app:latest
+
+
+            # Run the new Docker container
+            docker run -d --name sample-app -p 80:80 frengkysorituamanurung/sample-app:latest
+          '
