Setup CI/CD pipeline to deploy on Droplet Digital Ocean

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -52,15 +52,27 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     steps:
-      - name: Deploy to DigitalOcean Droplet
+      - name: Deploy to Droplet
         uses: appleboy/ssh-action@v0.1.3
         with:
           host: ${{ secrets.DROPLET_HOST }}
-          username: root
+          username: ${{ secrets.DROPLET_USER }}
           key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
           port: 22
           script: |
-            apt install docker.io
+            # Install Docker if not present
+            if ! [ -x "$(command -v docker)" ]; then
+              echo "Docker not found, installing..."
+              curl -fsSL https://get.docker.com -o get-docker.sh
+              sh get-docker.sh
+              sudo usermod -aG docker $USER
+              newgrp docker
+            else
+              echo "Docker is already installed"
+            fi
+
+            # Pull the latest Docker image and run it
             docker pull frengkysorituamanurung/sample-app:latest
-            docker run -d --name sample-app -p 80:8080 frengkysorituamanurung/sample-app:latest
-        
+            docker stop sample-app || true
+            docker rm sample-app || true
+            docker run -d --name sample-app -p 80:80 frengkysorituamanurung/sample-app:latest
